require('plugins')
require('treesitter-config')
require('lualine-config')
require('options')
require('bufferline-config')
require('nvimtree-config')
require('cmp-config')
require('lsp-config')
vim.cmd('colorscheme nightfox')
